### ISSUE TITLE
[BUG] Gitlab CI Shared-Runner tags

### ISSUE THREAD

**Issue by samq-ws** [whitesource-ft/ws-examples#86]
**Bug Description**  
The [GitLab CI examples](https://github.com/whitesource-ft/ws-examples/tree/main/CI-CD/GitLab) should either include instructions on using [shared runners](https://docs.gitlab.com/ee/user/gitlab_com/#shared-runners) and have an active/usable tag or we should remove the tag for ```- docker-runner``` so that the pipeline will auto pick.

**Comment by lukebroganws** [comment]
Removed tag from examples:
https://github.com/whitesource-ft/ws-examples/pull/87
